### ISSUE TITLE
大佬有没有成品出售啊

### ISSUE THREAD

**Issue by guanzi008** [peng-zhihui/Project-Quantum#1]
大佬赶紧发布教程，我去摸索看看能不能自己diy出来一个。

**Comment by peng-zhihui** [comment]
金手指版本的Quark-N核心板有在准备量产的哈

**Comment by guanzi008** [comment]
我要预订二个。

**Comment by guanzi008** [comment]
多少钱，支付宝多少我转给你。
我QQ245205080，weixin ：odatacc
好给你地址

**Comment by Libunko** [comment]
走众筹平台会不会更合适一点 ...

**Comment by peirancao** [comment]
大概什么时候可以买的到呢？

**Comment by QGB** [comment]
> 大佬赶紧发布教程，我去摸索看看能不能自己diy出来一个。

淘宝上应该有人在抄了

**Comment by DuyhStar** [comment]
这个自己diy打样成本真不低。

**Comment by jli113** [comment]
淘宝已经有预定了，店铺是seeedstudio企业店铺

**Comment by skywalkerRex** [comment]
求个链接，我淘宝没找到

jli113 <notifications@github.com>于2020年12月1日 周二下午11:32写道：

**Comment by jli113** [comment]
搜“迷你Linux开发板”就有了

**Comment by LeeHW-TW** [comment]
如果大佬确认，这就是官方版了吧？
![WechatIMG70](https://user-images.githubusercontent.com/47392753/100845309-fd675800-34b7-11eb-8652-894a2788653c.jpeg)

**Comment by jli113** [comment]
大佬确认过的
![image](https://user-images.githubusercontent.com/33822210/100845515-533c0000-34b8-11eb-9786-20eae99b2014.png)

**Comment by LeeHW-TW** [comment]
兄弟萌 冲！
