### ISSUE TITLE
有兄弟复现这个项目了吗

### ISSUE THREAD

**Issue by LeeHW-TW** [peng-zhihui/Project-Quantum#11]
可以把打样到复现的完整过程分享下吗
问了淘宝 说的几层板都不懂 萌新很懵

**Comment by Alansortorz** [comment]
光核心板裸板，不算SMT贴片都要五百，要做的话直接把PCB压缩文件上传到嘉立创客户端（可以百度看看怎么操作），若果自己焊的话开钢网划算一点




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "peng-zhihui/Project-Quantum"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月13日(星期二) 上午10:45
收件人:&nbsp;"peng-zhihui/Project-Quantum"<Project-Quantum@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[peng-zhihui/Project-Quantum] 有兄弟复现这个项目了吗 (#11)





 
可以把打样到复现的完整过程分享下吗
 问了淘宝 说的几层板都不懂 萌新很懵

**Comment by LeeHW-TW** [comment]
@Alansortorz 感谢回复。
😆这东西看的太懵了 ，而且打样5片起 感觉可以和别人拼单？
搞软件的看不懂这些玩意儿 -。- 没接触过

**Comment by Alansortorz** [comment]
不是有四块板子吗，你把规格，层数，全部记录下来，直接上传到嘉立创(流程百度有很多经验帖，找一个详细点的看一遍就明白了)，然后不想自己焊的话可以选择让他们帮你卖元器件，帮你贴片，可能很得花点钱，你自己评估一下继不继续做，小批量做价格肯定高，拼单你可以找几个人一块做，分担下成本，嘉立创的SMT贴片我没也用过，我有需求都是做板子自己焊的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "peng-zhihui/Project-Quantum"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月13日(星期二) 下午4:21
收件人:&nbsp;"peng-zhihui/Project-Quantum"<Project-Quantum@noreply.github.com&gt;;
抄送:&nbsp;"庞鸿"<1771453853@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [peng-zhihui/Project-Quantum] 有兄弟复现这个项目了吗 (#11)





 
@Alansortorz 感谢回复。
 😆这东西看的太懵了 ，而且打样5片起 感觉可以和别人拼单？
 搞软件的看不懂这些玩意儿 -。- 没接触过

**Comment by LeeHW-TW** [comment]
@Alansortorz 谢谢指导，我研究研究。

**Comment by LeeHW-TW** [comment]
@Alansortorz 请问一下，我在淘宝找人做，需要bom物料清单，这里面是不是没有呢？

**Comment by junchao-loongson** [comment]
我已经打板，系统启动成功！

**Comment by LeeHW-TW** [comment]
@junchao-loongson 可以加个联系方式交流一下咩？我也打板

**Comment by junchao-loongson** [comment]
@LeeHW-TW  可以邮件我 junchao_zhao@yeah.net

**Comment by LeeHW-TW** [comment]
@junchao-loongson 已发邮件，请回复 谢谢。

**Comment by GitKees** [comment]
> 我已经打板，系统启动成功！

做出来有多的吗？有的话，合适的价格入手一个。278238404@qq.com

**Comment by GitKees** [comment]
> @junchao-loongson 已发邮件，请回复 谢谢。



> 可以把打样到复现的完整过程分享下吗
> 问了淘宝 说的几层板都不懂 萌新很懵

你好，请问制作完成了？如果制作完成了，而且有多的，可以合适的价格转让一个吗？如
如果可以的话，请邮件联系我278238404@qq.com

**Comment by LeeHW-TW** [comment]
@GitKees 已经有官方合作的出售，在淘宝上面有预售
可见 #1

**Comment by fushenzhi** [comment]
> 
> 
> > @junchao-loongson 已发邮件，请回复 谢谢。
> 
> > 可以把打样到复现的完整过程分享下吗
> > 问了淘宝 说的几层板都不懂 萌新很懵
> 
> 你好，请问制作完成了？如果制作完成了，而且有多的，可以合适的价格转让一个吗？如
> 如果可以的话，请邮件联系我[278238404@qq.com](mailto:278238404@qq.com)

马家网站seeedstudio商铺买的已经到货性价比不错:http://dwz.date/dUGq

**Comment by franva** [comment]
你好 @junchao-loongson  请问 怎样做出BOM文件和 gerber文件啊?

我看中了zhihuijun的 FOC控制器, 拿去打板, 它们也问我要 BOM List还有 pick&place file. 
我很朦 不知道去哪里找这些文件.  已经瞎胡乱找 好久了, 不知所措....

希望大侠能拉我一把.

谢谢~!

**Comment by zhangxu1233** [comment]
> 你好 @junchao-loongson 请问 怎样做出BOM文件和 gerber文件啊?
> 
> 我看中了zhihuijun的 FOC控制器, 拿去打板, 它们也问我要 BOM List还有 pick&place file. 我很朦 不知道去哪里找这些文件. 已经瞎胡乱找 好久了, 不知所措....
> 
> 希望大侠能拉我一把.
> 
> 谢谢~!

自己ad打开工程然后导出
