### ISSUE TITLE
xrdp和vnc都无法成功连接远程桌面

### ISSUE THREAD

**Issue by kevintsq** [peng-zhihui/Project-Quantum#17]
在`Windows 10 Home 1909`多国语言版上，在同一局域网内，无论`Quark`是否通过`startx`进入了`GUI`模式，
`xrdp`连接基本每次都是这样的：
![image](https://user-images.githubusercontent.com/62129747/104549603-2b6eb900-566e-11eb-8ff7-8579df4c472d.png)
有时偶尔显示连接成功后，要么立刻退出，要么卡在一片灰色的界面上，光标是个叉子，没有任何反应。
`vnc`每次都是`The connection was refused by the computer`，没有任何错误信息。
![image](https://user-images.githubusercontent.com/62129747/104549832-8d2f2300-566e-11eb-820b-75059d4f44d4.png)
谷歌中英文搜索了各种常见处理方法，如重启、更新等，都无果。
请问可能是什么原因？如何解决？十分感谢！

**Comment by peng-zhihui** [comment]
https://wiki.seeedstudio.com/cn/Quantum-Mini-Linux-Development-Kit/


确认使用最新的镜像



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: kevintsq <notifications@github.com&gt;
发送时间: 2021年1月14日 13:50
收件人: peng-zhihui/Project-Quantum <Project-Quantum@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[peng-zhihui/Project-Quantum] xrdp和vnc都无法成功连接远程桌面 (#17)





 
在Windows 10 Home 1909多国语言版上，在同一局域网内，
 xrdp连接基本每次都是这样的：
 
 有时偶尔显示连接成功后，要么立刻退出，要么卡在一片灰色的界面上，光标是个叉子，没有任何反应。
 vnc每次都是The connection was refused by the computer，没有任何错误信息。
 
 谷歌中英文搜索了各种常见处理方法，如重启等，都无果。
 请问可能是什么原因？如何解决？十分感谢！

**Comment by kevintsq** [comment]
是使用的最新镜像……

**Comment by peng-zhihui** [comment]
你是不用root账户？用pi应该是没问题的

**Comment by kevintsq** [comment]
我用的就是pi，能登录，但无法使用，不知道是Win10的问题还是Quark的问题……关键是报错信息太有限……

**Comment by peng-zhihui** [comment]
重新烧写镜像，不要运行startx，然后用pi登陆远程就可以了。如果非得要在tty1（也就是lcd上面的终端）跑startx，那就加上sudo，这样就不会导致远程桌面不可用了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: kevintsq <notifications@github.com&gt;
发送时间: 2021年1月14日 22:10
收件人: peng-zhihui/Project-Quantum <Project-Quantum@noreply.github.com&gt;
抄送: 稚晖 <593245898@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[peng-zhihui/Project-Quantum] xrdp和vnc都无法成功连接远程桌面 (#17)

**Comment by genokolar** [comment]
win10登陆没问题，Android下微软的Remote desktop这个APP无法连接，显示协议有问题。但是其他软件（收费）连接没问题。

还有个问题是蓝牙无法连接BLE设备，还未找到解决办法。

**Comment by kevintsq** [comment]
可以了，赞赞！
