### ISSUE TITLE
语音助手唤醒没有反应

### ISSUE THREAD

**Issue by jli113** [peng-zhihui/Project-Quantum#18]
呼叫Pico没有反应，到.wukong目录下看了是.pmdl格式的私有模型。
不过snowboy的API全部下线了，找到了这个 https://github.com/seasalt-ai/snowboy

**Comment by peng-zhihui** [comment]
这个其实就是移植的wukong框架，到那时代码比较旧了，你可以按照官方教程自己安装一遍就行，麦克风和喇叭的配置我已经在系统中设置好了
