### ISSUE TITLE
语音助手是怎么实现的呢？

### ISSUE THREAD

**Issue by mailonghua** [peng-zhihui/Project-Quantum#19]
请教一下，语音助手是用的什么开源框架，能否分享一下资料介绍链接，非常感谢

**Comment by peng-zhihui** [comment]
知乎上找pico的文章



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Longhua <notifications@github.com&gt;
发送时间: 2021年1月19日 18:24
收件人: peng-zhihui/Project-Quantum <Project-Quantum@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[peng-zhihui/Project-Quantum] 语音助手是怎么实现的呢？ (#19)





 
请教一下，语音助手是用的什么开源框架，能否分享一下资料介绍链接，非常感谢

**Comment by mailonghua** [comment]
多谢
但Snowboy好像已经停止维护更新了，还有更好的开源推荐吗

**Comment by jli113** [comment]
#18
