### ISSUE TITLE
Quark-N的相关PCB文件是不开源项目？

### ISSUE THREAD

**Issue by PandaTAT** [peng-zhihui/Project-Quantum#20]
你好稚晖君，我想问一下Quark-N的相关PCB设计文件是属于不开源项目吗？还是暂时还没空将文件整理并上传。想用来学习一下，并且对自己动手有非常高的兴趣

**Comment by cgrrty** [comment]
开源的， 仔细看资料硬件部分， ad画的

**Comment by PandaTAT** [comment]
> 开源的，仔细看资料硬件部分，ad画的

我翻看了Hardware文件夹好像确实没有QuarK-N量产版的PCB文件，只有邮票孔式的相关PCB文件

**Comment by DedongZhang** [comment]
> > 开源的，仔细看资料硬件部分，ad画的
> 
> 我翻看了Hardware文件夹好像确实没有QuarK-N量产版的PCB文件，只有邮票孔式的相关PCB文件

金手指版本的厂商有提供开源文件，地址在这里 https://files.seeedstudio.com/wiki/Quantum-Mini-Linux-Dev-Kit/Atom-Shield-N-AD-files.zip

**Comment by QinXi2019** [comment]
Quark-N在bilibili看到大佬的回复说，Quark-N是跟别人（SeeedStudio）合作量产的，也要恰饭的，所以不开源，厂家只开源了Quark-N的底板Atom-N
