### ISSUE TITLE
关于项目结构的一些建议

### ISSUE THREAD

**Issue by KortanZ** [peng-zhihui/Project-Quantum#4]
个人感觉这个项目所有硬件软件文件都放在一个 repo 里，clone 的时候太耗时间了，而且不方便管理。可以申请一个专门的 Project-Quantum 的 github organization 账户，下面放各个子项目，如果有幸项目能发展起来，社区对各个子项目也好维护，这点，可以参考 [clockworkpi](https://github.com/clockworkpi) 这个开源项目。

**Comment by peng-zhihui** [comment]
多谢建议，我后面会考虑的

**Comment by pengzi007** [comment]
反倒觉得放到一起更加清晰，只有第一次clone的时候会比较耗时，后面pull的时候只更新变更的内容。分开的话不能保证所有项目都是最新的，需要分别做pull。
