### ISSUE TITLE
最新的Image 显示128GB SD卡只有2GB剩余 

### ISSUE THREAD

**Issue by franva** [peng-zhihui/Project-Quantum#42]
![image](https://user-images.githubusercontent.com/5151146/151921202-c423e6a8-bcf7-4007-8c8f-72f00e9d4b40.png)

我新打开了一个128GB的SD， 但是好像系统并不能识别SD的容量， 如上图。

![image](https://user-images.githubusercontent.com/5151146/151935368-8b304312-cfdd-4042-9aba-67ae0f2f7203.png)

再来一个更全面的图

求助各位大神指点。  谢谢 

@peng-zhihui  @stig3 @Coder-Chouchou

**Comment by franva** [comment]
![image](https://user-images.githubusercontent.com/5151146/151935950-56a2f60b-033e-4e64-9cb0-d1fdcadc31ac.png)

用了 fdisk看了一下 发现 好像能发现 119GB的盘， 但是 不知道为什么 GUI里面不显示。

**Comment by zhouchunyuan** [comment]
可以把SD卡插取下来，用sd卡读卡器（或是tf-usb读卡器）插到另一台linux电脑上（或是用emmc启动quark，把sd卡当U盘插上）, 然后用Gparted扩展分区就可以了。可以参考coolflyreg在B站的视频

**Comment by wc7086** [comment]
> 然后用Gparted扩展分区

直接用fdisk或者cfdisk（有UI）就好了

**Comment by franva** [comment]
多谢二位. 后来发现的确是装完镜像后 分区只有一点点的原因. 

用了 GParted就好了.
