### ISSUE TITLE
请问如何扩容当前存储空间，SD卡可使用大小与实际大小不符。

### ISSUE THREAD

**Issue by eternal-echo** [peng-zhihui/Project-Quantum#48]
![E7 }3476{58S7}12C 2{W$8](https://user-images.githubusercontent.com/78364027/179660780-6537b98a-0c5e-4d0b-bcd3-ce864d6e1787.png)  
使用了32GB的SD卡烧录系统镜像，运行`df -h`命令显示总存储空间只有8G，请问要如何扩容呢。  
尝试了网上常用的fdisk进行分区扩展，但是最后有一步格式化，而我的SD卡是系统盘，就不太敢往下操作了，有没有熟悉这块的大佬指点一下，感谢。

**Comment by peng-zhihui** [comment]
用gparted一键扩容就行了，图形化的界面一看就明白了。如果夸克上没有安装图形界面的话，也可以把sd卡插在PC上用虚拟机里面的gparted操作。

**Comment by eternal-echo** [comment]
# gparted扩展磁盘
感谢稚辉大佬的指点，之前一直固执的认为包含了系统的sd卡只能在夸克上进行分区操作，原来可以直接在其他主机上进行修改分区操作。使用Ubuntu虚拟机上成功完成。
## 打开sd卡
将sd卡插入扩展坞，接入笔记本。然后打开虚拟机，将该usb设备添加到虚拟机中。
![Pasted image 20220719145842](https://user-images.githubusercontent.com/78364027/179688599-7c80247b-8a5b-49a5-8993-9403f174acc6.png)
## 运行gparted
命令行中输入`gparted`，输入密码后即可对分区进行操作。
选择/dev/sdb设备，点击右键分区的图形区域，选择更改大小移动，点击确认按钮，等待操作完成即可。
![Pasted image 20220719150039](https://user-images.githubusercontent.com/78364027/179688640-a79e62c1-663d-444e-b315-67662fca3be3.png)

**Comment by eternal-echo** [comment]
> 用gparted一键扩容就行了，图形化的界面一看就明白了。如果夸克上没有安装图形界面的话，也可以把sd卡插在PC上用虚拟机里面的gparted操作。

还有个小问题，请问夸克上怎样打开图形界面呢，是在npi-config上修改吗？或者需要另外安装？然后图形界面是在那块小屏幕上显示还是在远程电脑中显示呢？
感谢🙏

**Comment by peng-zhihui** [comment]
默认镜像已经安装了xfce图形桌面了，用Windows自带的远程桌面登录就行

**Comment by eternal-echo** [comment]
感谢
