### ISSUE TITLE
Quark-N金手指核心板没有以太网的引脚吗？

### ISSUE THREAD

**Issue by eternal-echo** [peng-zhihui/Project-Quantum#49]
Quark邮票孔核心板还是有以太网引脚的，金手指版本好像直接引脚都没拉出来嘛？项目需要使用以太网接口，准备改一下底板，发现好像没有这个引脚。

**Comment by Mehver** [comment]
![image](https://user-images.githubusercontent.com/75297777/180819950-7a761105-cfc4-462e-a8f3-7869932f8eda.png)

有的，`69` `71` `73` `75` 四个引脚

**Comment by eternal-echo** [comment]
> ![image](https://user-images.githubusercontent.com/75297777/180819950-7a761105-cfc4-462e-a8f3-7869932f8eda.png)
> 
> 有的，`69` `71` `73` `75` 四个引脚


但是好像没有拉出这些引脚，老版本的核心板倒是有，估计只得用邮票孔的了
![image](https://user-images.githubusercontent.com/78364027/180903454-a26e5e24-21a5-4ad0-a9c9-be0a35a82ce8.png)

**Comment by peng-zhihui** [comment]
金手指的没有，放不下了

**Comment by eternal-echo** [comment]
> 金手指的没有，放不下了

好的了解了，感谢
