### ISSUE TITLE
无法拓展根目录分区大小

### ISSUE THREAD

**Issue by Lumorian** [peng-zhihui/Project-Quantum#54]
![-599033bb74e52c8.jpg](https://user-images.githubusercontent.com/102412546/186078452-67d1c533-a3d1-46e0-9fd3-397ccc5ce799.jpg)![1e846aa77f0a4658.jpg](https://user-images.githubusercontent.com/102412546/186078453-6f9d3481-09be-4b2b-a9da-e458add9ef7b.jpg)

**Comment by peng-zhihui** [comment]
不能扩展正在用的磁盘，把卡插到电脑虚拟机上扩展
