### ISSUE TITLE
能支持全志H6吗。

### ISSUE THREAD

**Issue by guanzi008** [peng-zhihui/Project-Quantum#6]
看了下H6支持usb3.0

**Comment by boblvcn** [comment]
引脚定义都不一样，很明显不能。

**Comment by guanzi008** [comment]
> 引脚定义都不一样，很明显不能。

知道不能，就是希望有人能适配画出h6的pcb版因为h6支持usb3.0和千兆网卡，。。。

**Comment by kingo132** [comment]
顺便搞个5gwifi，2.4g有点弱，哈哈。。

**Comment by how0723** [comment]
H3比较适合嵌入式项目，电路简单，性能不弱，大疆无人机里面用的就是H3
