### ISSUE TITLE
催更~

### ISSUE THREAD

**Issue by junchao-loongson** [peng-zhihui/Project-Quantum#8]
大佬，kernel和image多久更新呀

**Comment by yaolet** [comment]
吊了那么多年的鱼，就是为了自己涨点粉，问量产，一年多还是这句话，说开源，不给kernel和image。你们都还当真了

**Comment by peng-zhihui** [comment]
@yaolet 兄弟要不你来开个源？就你这态度做技术永远也就是个半吊子了啊🙂
有没有量产看截图吧，不要张口就来。我readme里面说得不够清楚吗，工作繁忙抽空更新还欠你的了？仓库里开源这么多东西都是逗你玩的？我的收入可不需要靠这些来涨你这样的粉，欢迎取关哈。

**Comment by peng-zhihui** [comment]
@yaolet 兄弟要不你来开个源？就你这态度做技术永远也就是个半吊子了啊🙂
有没有量产看截图吧，不要张口就来。我readme里面说得不够清楚吗，工作繁忙抽空更新还欠你的了？仓库里开源这么多东西都是逗你玩的？我的收入可不需要靠这些来涨你这样的粉，欢迎取关哈。

**Comment by peng-zhihui** [comment]
@yaolet 兄弟要不你来开个源？就你这态度做技术永远也就是个半吊子了啊🙂
有没有量产看截图吧，不要张口就来。我readme里面说得不够清楚吗，工作繁忙抽空更新还欠你的了？仓库里开源这么多东西都是逗你玩的？我的收入可不需要靠这些来涨你这样的粉，欢迎取关哈。

**Comment by peng-zhihui** [comment]
@yaolet 兄弟要不你来开个源？就你这态度做技术永远也就是个半吊子了啊🙂
有没有量产看截图吧，不要张口就来。我readme里面说得不够清楚吗，工作繁忙抽空更新还欠你的了？仓库里开源这么多东西都是逗你玩的？我的收入可不需要靠这些来涨你这样的粉，欢迎取关哈。

**Comment by adsl7878778** [comment]
讲道理，原理图都给你了，用那些引脚，自己去设备树里动手写写不就完了，自己生成自己能用的image不好吗，啥都想要现成的，你是淘宝来的吧



---原始邮件---
发件人: "yaolet"<notifications@github.com&gt;
发送时间: 2020年9月22日(周二) 凌晨5:50
收件人: "peng-zhihui/Project-Quantum"<Project-Quantum@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [peng-zhihui/Project-Quantum] 催更~ (#8)




 
吊了那么多年的鱼，就是为了自己涨点粉，问量产，一年多还是这句话，说开源，不给kernel和image。你们都还当真了

**Comment by peng-zhihui** [comment]
![Uploading 微信图片_20200922085421.jpg…]()

**Comment by peng-zhihui** [comment]
![微信图片_20200922085421](https://user-images.githubusercontent.com/12994887/93835320-6c068900-fcb1-11ea-8335-56d9807dd6b1.jpg)

**Comment by junchao-loongson** [comment]
@peng-zhihui ,晖哥，核心板开板，板厚选多少呀，我不太懂高速板，听说有讲究，特此请教下，比赛准备用这个板，开板还有哪些工艺参数要注意的么

**Comment by peng-zhihui** [comment]
@junchao-loongson 工艺可以看这个图，我是在博运发加工的，个人做板子会比较贵，而且最重要的是手工焊接非常麻烦。如果不急的话，可以等我后面量产版出来，跟SEEED那边已经在合作试产了，顺利的话11月左右可以正式量产的；如果很急用，可以去TB买一些其他的H3/H5核心板，除了尺寸会大一点别的都基本通用的。

**Comment by junchao-loongson** [comment]
> @junchao-loongson 工艺可以看这个图，我是在博运发加工的，个人做板子会比较贵，而且最重要的是手工焊接非常麻烦。如果不急的话，可以等我后面量产版出来，跟SEEED那边已经在合作试产了，顺利的话11月左右可以正式量产的；如果很急用，可以去TB买一些其他的H3/H5核心板，除了尺寸会大一点别的都基本通用的。
> 
> ![微信图片_20200922100420](https://user-images.githubusercontent.com/12994887/93838091-03bca500-fcbb-11ea-8dfc-48ad1d0d6f74.jpg)

非常感谢，打板确实好贵。。。。

**Comment by junchao-loongson** [comment]
@peng-zhihui  辉哥，我们板子开回来了，底板自己画的。测试时候底板对核心板供电5V，然后接了SD 到SD0，板子上电后debug串口没输出，这时电流有90mA左右。
想问问大佬有没有啥调试建议，感觉像SD卡没读到，调了很久也不行，求指点

**Comment by yaolet** [comment]
> @yaolet 兄弟要不你来开个源？就你这态度做技术永远也就是个半吊子了啊slightly_smiling_face
> 有没有量产看截图吧，不要张口就来。我readme里面说得不够清楚吗，工作繁忙抽空更新还欠你的了？仓库里开源这么多东西都是逗你玩的？我的收入可不需要靠这些来涨你这样的粉，欢迎取关哈。

真有意思，又不是我在催你。你爱干嘛干嘛。
